### ISSUE TITLE
Blocks out of sync

### ISSUE THREAD

**Issue by chinh7** [mhanne/bitcoin-ruby-node#3]
Hello, our bitcoin ruby node seems to stop getting new blocks, and the client info shows block sync = false.
Any advice? Thanks

``` bash
%# bitcoin_node_cli info
{
  "blocks": {
    "height": 358906,
    "depth": 358906,
    "peers": 351929,
    "sync": false
  }
}
```

**Comment by mhanne** [comment]
Hi, 
which storage backend and adapter are you using?
The node on webbtc is running with the `archive` backend on a postgres db, and seems fine.

Please run the node with `--verbose` and look for validation errors when it tries to process the very first block it received. Add `--die-on-orphan` if the relevant part gets spammed away too quickly by "orphan" blocks.

**Comment by chinh7** [comment]
Yes we have the same storage configuration. The server was down and when it got back on the node went out of sync. It probably was a db problem. Anyways I decided to set up a new node and things seem to be ok now. Thank you
